NAME HOOKS

; Consts

; Offsets
#define _Settings_Load 09a96h
#define _MAIN_SCREEN_KEY_HANDLER_FUNC 02cb8h
#define _UI_DrawSmallText 0xcd14
#define _Display_DrawBitmap_16x16 0x99a5
#define _RF_Write 0xE6A3


; uMod settings in XDATA
#define _UMOD_SETTINGS_FILTER_FREQ 0FF0h
#define _UMOD_SETTINGS_LIGHT_THEME 0FF1h
#define _UMOD_SETTINGS_OPT_FLAGS   0FF2h
#define _UMOD_SETTINGS_MODE_OVRD   0FF3h
#define _UMOD_MENU_ACTIVE_BIT      02Fh.7

; External C functions
EXTRN CODE (uMod_Startup)
EXTRN CODE (uMod_HotkeyHook)
EXTRN CODE (uMod_HandleMenuKeys)
EXTRN CODE (uMod_DrawSignalStrengthHook)
EXTRN CODE (uMod_DrawBattery)
EXTRN CODE (uMod_GetModeOverrideString)
EXTRN CODE (uMod_ModulationOverrideHook)

; Hooks
?PR?_MAIN_INIT_HOOK?HOOKS SEGMENT CODE
?PR?_MAIN_LOOP_HOOK?HOOKS SEGMENT CODE
?PR?_POINTER_COLOR_HOOK?HOOKS SEGMENT CODE
?PR?_FMFREQ_COLOR_HOOK?HOOKS SEGMENT CODE
?PR?_RF_FILTER_FREQ_HOOK?HOOKS SEGMENT CODE
?PR?_RF_OPENRX_HOOK?HOOKS SEGMENT CODE
?PR?_RADIO_OPENRX_HOOK?HOOKS SEGMENT CODE
?PR?_MAIN_SCREEN_KEY_HANDLER_HOOK?HOOKS SEGMENT CODE
?PR?_TASK_HANDLE_KEYS_HOOK?HOOKS SEGMENT CODE
?PR?_MEDIUM_TO_SMALL_TEXT_HOOK?HOOKS SEGMENT CODE
?PR?_MEDIUM_TO_SMALL_STATUS_TEXT_HOOK?HOOKS SEGMENT CODE
?PR?_DRAW_SIGNAL_STRENGTH_HOOK?HOOKS SEGMENT CODE
?PR?_TIMER_HOOK_10MS?HOOKS SEGMENT CODE
?PR?_BATTERY_UPDATE_HOOK?HOOKS SEGMENT CODE
?PR?_BATTERY_DRAW_HOOK?HOOKS SEGMENT CODE
?PR?_CH_VFO_TEXT_COLOR_HOOK?HOOKS SEGMENT CODE
?PR?_MODULATION_TEXT_HOOK?HOOKS SEGMENT CODE
?PR?_OPEN_TX_HOOK?HOOKS SEGMENT CODE
?PR?_OPEN_RX_HOOK?HOOKS SEGMENT CODE
?PR?_HANDLE_PTT1_HOOK?HOOKS SEGMENT CODE
?PR?_HANDLE_PTT2_HOOK?HOOKS SEGMENT CODE

;
; Main init hook
;
PUBLIC _MAIN_INIT_HOOK
RSEG ?PR?_MAIN_INIT_HOOK?HOOKS
_MAIN_INIT_HOOK:
	USING	0

	LCALL uMod_Startup
	LJMP _Settings_Load
; END OF _MAIN_INIT_HOOK


;
; Main loop hook
;
PUBLIC _MAIN_LOOP_HOOK
RSEG ?PR?_MAIN_LOOP_HOOK?HOOKS
_MAIN_LOOP_HOOK:
	USING 0

	JNB _UMOD_MENU_ACTIVE_BIT, _MAIN_LOOP_ORIG
	LJMP 08b4bh ; Go to the beginning of the loop

_MAIN_LOOP_ORIG:
	JNB 02Ch.3, _MAIN_LOOP_HOOK_BRANCH_TAKEN ; Original instruction
	LJMP 08b68h

_MAIN_LOOP_HOOK_BRANCH_TAKEN:
	LJMP 08b73h ; Do tasks

; END OF _MAIN_LOOP_HOOK


;
; Change color of the pointers
;
PUBLIC _POINTER_COLOR_HOOK
RSEG ?PR?_POINTER_COLOR_HOOK?HOOKS
_POINTER_COLOR_HOOK:
	USING 0
	
	MOV DPTR, #_UMOD_SETTINGS_LIGHT_THEME
	MOVX A, @DPTR
	JZ _POINTER_COLOR_ORIG

	; Invert text color
	MOV 05Fh, #0FFh
	MOV R3, #0FFh
	CLR A
	MOV 060h, A
	MOV 061h, A
	RET
	
_POINTER_COLOR_ORIG:
	; Original instructions
	MOV 05Fh, #01Fh
	CLR A
	MOV 060h, A
	MOV 061h, A
	MOV R3, A
	RET
; END OF _POINTER_COLOR_HOOK


;
; Change color for the FM frequency text
;
PUBLIC _FMFREQ_COLOR_HOOK
RSEG ?PR?_FMFREQ_COLOR_HOOK?HOOKS
_FMFREQ_COLOR_HOOK:
	USING 0
	
	MOV DPTR, #_UMOD_SETTINGS_LIGHT_THEME
	MOVX A, @DPTR
	JZ _FMFREQ_COLOR_ORIG

	; Invert text color
	MOV 054H, #0BEh
	MOV 055H, #00Eh
	CLR A
	RET
	
_FMFREQ_COLOR_ORIG:
	; Original instructions
	MOV 054H, #00Eh
	MOV 055H, #0FFh
	CLR A
	RET
; END OF _FMFREQ_COLOR_HOOK


;
; VHF/UHF filter border frequency selection
;
PUBLIC _RF_FILTER_FREQ_HOOK
RSEG ?PR?_RF_FILTER_FREQ_HOOK?HOOKS
_RF_FILTER_FREQ_HOOK:
	USING 0
	
	MOV DPTR, #_UMOD_SETTINGS_FILTER_FREQ
	MOVX A, @DPTR	
	MOV DPTR, #_RF_FILTER_FREQ_DEFAULT
	MOV B, #9
	MUL AB
	JMP @A+DPTR

_RF_FILTER_FREQ_DEFAULT:
    ; Original instructions (300 MHz)
	MOV R7, #080h
	MOV R6, #0C3h
	MOV R5, #0C9h
	MOV R4, #001h
	RET

_RF_FILTER_FREQ_280:
	MOV R7, #000h
	MOV R6, #03Fh
	MOV R5, #0ABh
	MOV R4, #001h
	RET
	
_RF_FILTER_FREQ_270:
	MOV R7, #0C0h
	MOV R6, #0FCh
	MOV R5, #09Bh
	MOV R4, #001h
	RET
	
_RF_FILTER_FREQ_265:
	MOV R7, #0A0h
	MOV R6, #05Bh
	MOV R5, #094h
	MOV R4, #001h
	RET
; END OF _RF_FILTER_FREQ_HOOK


;
; RF_OpenRx hook for modulation override
;
PUBLIC _RF_OPENRX_HOOK
RSEG ?PR?_RF_OPENRX_HOOK?HOOKS
_RF_OPENRX_HOOK:
	MOV DPTR, #_UMOD_SETTINGS_MODE_OVRD
	MOVX A, @DPTR
	
	DEC A
	JZ _RF_OPENRX_HOOK_MOD_AM
	
	DEC A
	JZ _RF_OPENRX_HOOK_MOD_FM
	
	DEC A
	JZ _RF_OPENRX_HOOK_MOD_USB
	
	SJMP _RF_OPENRX_HOOK_WRITE

_RF_OPENRX_HOOK_MOD_FM:
	MOV R3, #0x40
	MOV R5, #0x61
	SJMP _RF_OPENRX_HOOK_WRITE
	
_RF_OPENRX_HOOK_MOD_AM:
	MOV R3, #0x40
	MOV R5, #0x67
	SJMP _RF_OPENRX_HOOK_WRITE

_RF_OPENRX_HOOK_MOD_USB:
	MOV R3, #0x40
	MOV R5, #0x65
	SJMP _RF_OPENRX_HOOK_WRITE

_RF_OPENRX_HOOK_WRITE:
	LJMP _RF_Write
; END OF _RF_OPENRX_HOOK


;
; RADIO_OpenRx hook for modulation override
;
PUBLIC _RADIO_OPENRX_HOOK
RSEG ?PR?_RADIO_OPENRX_HOOK?HOOKS
_RADIO_OPENRX_HOOK:
	MOV DPTR, #_UMOD_SETTINGS_MODE_OVRD
	MOVX A, @DPTR
	JZ _RADIO_OPENRX_SKIP

	LJMP uMod_ModulationOverrideHook
	
_RADIO_OPENRX_SKIP:
	LJMP 0xd3ab
; END OF _RADIO_OPENRX_HOOK


;
; Main screen key handler hook
;
PUBLIC _MAIN_SCREEN_KEY_HANDLER_HOOK
RSEG ?PR?_MAIN_SCREEN_KEY_HANDLER_HOOK?HOOKS
_MAIN_SCREEN_KEY_HANDLER_HOOK:
	USING 0
	
	LCALL uMod_HotkeyHook
	LCALL _MAIN_SCREEN_KEY_HANDLER_FUNC ; Original instruction
	RET
	
; END OF _MAIN_SCREEN_KEY_HANDLER_HOOK


;
; Global keys handler hook
;
PUBLIC _TASK_HANDLE_KEYS_HOOK
RSEG ?PR?_TASK_HANDLE_KEYS_HOOK?HOOKS
_TASK_HANDLE_KEYS_HOOK:
	USING 0

	JNB _UMOD_MENU_ACTIVE_BIT, _TASK_HANDLE_KEYS_ORIG
	LJMP uMod_HandleMenuKeys

_TASK_HANDLE_KEYS_ORIG:
	; Original instructions
	JNB 028h.6, _TASK_HANDLE_KEYS_ORIG_JMP_TARGET 
	LCALL 08809h ; MENU_HandleOptionKeys

_TASK_HANDLE_KEYS_ORIG_JMP_TARGET:
	LJMP 0c338h

; END OF _TASK_HANDLE_KEYS_HOOK


;
; Medium to small text hook
;
PUBLIC _MEDIUM_TO_SMALL_TEXT_HOOK
RSEG ?PR?_MEDIUM_TO_SMALL_TEXT_HOOK?HOOKS
_MEDIUM_TO_SMALL_TEXT_HOOK:
	; Backup INTMEM 0x4E (Y)
	;MOV 059h, 04Eh
	
	MOV 043h, 053h
	MOV 044h, 054h
	MOV 045h, 055h
	LJMP _UI_DrawSmallText
	;LCALL _UI_DrawSmallText
	
	; Restore INTMEM 0x4E (Y)
	;MOV 04Eh, 059h
	;RET
; END OF _MEDIUM_TO_SMALL_TEXT_HOOK


;
; Medium to small status text hook
;
PUBLIC _MEDIUM_TO_SMALL_STATUS_TEXT_HOOK
RSEG ?PR?_MEDIUM_TO_SMALL_STATUS_TEXT_HOOK?HOOKS
_MEDIUM_TO_SMALL_STATUS_TEXT_HOOK:
	; Backup INTMEM 0x4E (Y)
	MOV 059h, 04Eh
	
	; Set Y=6
	MOV 053h, #6
	MOV 054H, #079h
	MOV 055H, #0CEh
	LCALL _MEDIUM_TO_SMALL_TEXT_HOOK
	
	; Restore INTMEM 0x4E (Y)
	MOV 04Eh, 059h

	RET
; END OF _MEDIUM_TO_SMALL_STATUS_TEXT_HOOK


;
; Draw signal strength (level) hook
;
PUBLIC _DRAW_SIGNAL_STRENGTH_HOOK
RSEG ?PR?_DRAW_SIGNAL_STRENGTH_HOOK?HOOKS
_DRAW_SIGNAL_STRENGTH_HOOK:
	USING 0
	
	LCALL _Display_DrawBitmap_16x16 ; Original instruction
	LJMP uMod_DrawSignalStrengthHook
; END OF _DRAW_SIGNAL_STRENGTH_HOOK


;
; Timer hook for RSSI update (50ms to 10ms)
;
PUBLIC _TIMER_HOOK_10MS
RSEG ?PR?_TIMER_HOOK_10MS?HOOKS
_TIMER_HOOK_10MS:			
	; Original instruction
	MOV 008h, #0
	
	; Set UpdateRSSI bit
	SETB 027h.3
	
	RET
; END OF _TIMER_HOOK_10MS


;
; Battery level update hook
;
PUBLIC _BATTERY_UPDATE_HOOK
RSEG ?PR?_BATTERY_UPDATE_HOOK?HOOKS
_BATTERY_UPDATE_HOOK:
	MOV DPTR, #0xFF2
	MOVX A, @DPTR
	
	; Restore original pointer
	MOV DPTR, #0x4e1
	
	RRC A
	RRC A
	ANL A, #3
	JNZ _BATTERY_UPDATE_AFTER_LEVEL_CMP
	LJMP 0D0C5h

_BATTERY_UPDATE_AFTER_LEVEL_CMP:
	LJMP 0D0C9h
; END OF _BATTERY_UPDATE_HOOK


;
; Battery draw hook
;
PUBLIC _BATTERY_DRAW_HOOK
RSEG ?PR?_BATTERY_DRAW_HOOK?HOOKS
_BATTERY_DRAW_HOOK:
	MOV DPTR, #0xFF2
	MOVX A, @DPTR
	RRC A
	RRC A
	ANL A, #3
	JNZ _BATTERY_DRAW_CUSTOM
	
	; Call original function (draw bitmap)
	LJMP 099A5h

_BATTERY_DRAW_CUSTOM:
	LJMP uMod_DrawBattery
	
; END OF _BATTERY_DRAW_HOOK


;
; Modulation text hook
;
PUBLIC _MODULATION_TEXT_HOOK
RSEG ?PR?_MODULATION_TEXT_HOOK?HOOKS
_MODULATION_TEXT_HOOK:
	; Original instruction
	MOV DPTR, #_UMOD_SETTINGS_MODE_OVRD
	MOVX A, @DPTR
	JZ _MODULATION_TEXT_ORIG

	; Zeroing kill/stun flags
	LCALL uMod_GetModeOverrideString

_MODULATION_TEXT_ORIG:
	; Original instruction
	LJMP 0xaecd ; UI_DrawMediumText
	
; END OF _MODULATION_TEXT_HOOK


;
; Status bar text color hook
;
PUBLIC _CH_VFO_TEXT_COLOR_HOOK
RSEG ?PR?_CH_VFO_TEXT_COLOR_HOOK?HOOKS
_CH_VFO_TEXT_COLOR_HOOK:
	MOV DPTR, #_UMOD_SETTINGS_LIGHT_THEME
	MOVX A, @DPTR
	JZ _CH_VFO_TEXT_COLOR_ORIG

	MOV 054H, #03Ch ; #03Fh 
	MOV 055H, #034h ; #014h 
	RET

_CH_VFO_TEXT_COLOR_ORIG:
	MOV 054H, #0C3h ; #0C0h 
	MOV 055H, #0CBh ; #0EBh 
	RET
; END OF _CH_VFO_TEXT_COLOR_HOOK


;
; Open Tx hook
;
PUBLIC _OPEN_TX_HOOK
RSEG ?PR?_OPEN_TX_HOOK?HOOKS
_OPEN_TX_HOOK:
	LCALL 0xaa64 ; CHANNEL_LoadCurrentChannels
	LCALL 0x916a 

	; Original instruction
	MOV DPTR, #0x2b8
	LJMP 0x527a

; END OF _OPEN_TX_HOOK


;
; Open Rx hook
;
PUBLIC _OPEN_RX_HOOK
RSEG ?PR?_OPEN_RX_HOOK?HOOKS
_OPEN_RX_HOOK:
	; Option is off
    MOV DPTR, #_UMOD_SETTINGS_OPT_FLAGS
	MOVX A, @DPTR
	JNB ACC.5, _OPEN_RX_ORIG

	; If Dual Watch is on
	MOV DPTR, #0x146
	MOVX A, @DPTR
	JNB ACC.2, _OPEN_RX_ORIG
	
	; Load current channel into ACC+DPTR
	LCALL 0x6a51 
	
	; Set current/selected channel
	JNB 027h.4, _OPEN_RX_SELECT_A ; RADIO_RxDualWatchChannelAB
	ORL A, #0x1
	SJMP _OPEN_RX_UPDATE
	
_OPEN_RX_SELECT_A:
	; Select channel A
	ANL A, #0xFE

_OPEN_RX_UPDATE:
	; Update current channel
	MOVX @DPTR, A
	
	; Reload frequency, settings etc.
	LCALL 0xaa64
	LCALL 0x8e15 ; Update screen

_OPEN_RX_ORIG:
	; Original instruction
	CLR A
	MOV DPTR, #0x2e4
	RET

; END OF _OPEN_RX_HOOK


;
; PTT #1 hook for dual watch
;
PUBLIC _HANDLE_PTT1_HOOK
RSEG ?PR?_HANDLE_PTT1_HOOK?HOOKS
_HANDLE_PTT1_HOOK:
	JNB ACC.2, _HANDLE_PTT1_SKIP
	
    MOV DPTR, #_UMOD_SETTINGS_OPT_FLAGS
	MOVX A, @DPTR
	JB ACC.4, _HANDLE_PTT1_SKIP
	
	; Original instruction
	LJMP 0x6200
	
_HANDLE_PTT1_SKIP:
	LJMP 0x61eb


;
; PTT #2 hook for dual watch
;
PUBLIC _HANDLE_PTT2_HOOK
RSEG ?PR?_HANDLE_PTT2_HOOK?HOOKS
_HANDLE_PTT2_HOOK:
	JNB ACC.2, _HANDLE_PTT2_SKIP
	
    MOV DPTR, #_UMOD_SETTINGS_OPT_FLAGS
	MOVX A, @DPTR
	JB ACC.4, _HANDLE_PTT2_SKIP
	
	; Original instruction
	LJMP 0x622b
	
_HANDLE_PTT2_SKIP:
	LJMP 0x6216
	
; END OF _HANDLE_PTT2_HOOK


END