extern void uMod_DrawLogoHook();
extern void uMod_HotkeyHook();
extern void uMod_HandleMenuKeys();
extern void uMod_DrawPowerMeter();
extern void uMod_ResetKillStun();
extern void uMod_FrequencyColorHook();
extern void uMod_DrawStatusBarSeparatorHook();
extern void _MAIN_INIT_HOOK();
extern void _MAIN_LOOP_HOOK();
extern void _POINTER_COLOR_HOOK();
extern void _FMFREQ_COLOR_HOOK();
extern void _RF_FILTER_FREQ_HOOK();
extern void _MAIN_SCREEN_KEY_HANDLER_HOOK();
extern void _TASK_HANDLE_KEYS_HOOK();
extern void _MEDIUM_TO_SMALL_TEXT_HOOK();
extern void _DRAW_SIGNAL_STRENGTH_HOOK();
extern void _TIMER_HOOK_10MS();
extern void _RF_OPENRX_HOOK();
extern void _RADIO_OPENRX_HOOK();
extern void _MEDIUM_TO_SMALL_STATUS_TEXT_HOOK();
extern void _BATTERY_UPDATE_HOOK();
extern void _BATTERY_DRAW_HOOK();
extern void _CH_VFO_TEXT_COLOR_HOOK();
extern void _MODULATION_TEXT_HOOK();
extern void _OPEN_TX_HOOK();
extern void _OPEN_RX_HOOK();
extern void _HANDLE_PTT1_HOOK();
extern void _HANDLE_PTT2_HOOK();

void main(void) {
	_MAIN_INIT_HOOK();
	_MAIN_LOOP_HOOK();
	_POINTER_COLOR_HOOK();
	_FMFREQ_COLOR_HOOK();
	_RF_FILTER_FREQ_HOOK();
	_MAIN_SCREEN_KEY_HANDLER_HOOK();
	_TASK_HANDLE_KEYS_HOOK();
	_MEDIUM_TO_SMALL_TEXT_HOOK();
	_DRAW_SIGNAL_STRENGTH_HOOK();
	_TIMER_HOOK_10MS();
	_RF_OPENRX_HOOK();
	_RADIO_OPENRX_HOOK();
	_MEDIUM_TO_SMALL_STATUS_TEXT_HOOK();
	_BATTERY_UPDATE_HOOK();
	_BATTERY_DRAW_HOOK();
	_CH_VFO_TEXT_COLOR_HOOK();
	_MODULATION_TEXT_HOOK();
	_OPEN_TX_HOOK();
	_OPEN_RX_HOOK();
	_HANDLE_PTT1_HOOK();
	_HANDLE_PTT2_HOOK();

	uMod_DrawPowerMeter();
	uMod_HandleMenuKeys();
	uMod_HotkeyHook();
	uMod_DrawLogoHook();
	uMod_ResetKillStun();
	uMod_FrequencyColorHook();
	uMod_DrawStatusBarSeparatorHook();
}
