#ifndef __SMETER_H__
#define __SMETER_H__

#define SIGNAL_METER_X 2
#define SIGNAL_METER_LEVEL_WIDTH 10
#define SIGNAL_METER_LEVEL_COUNT 7 /* from S1/S2 */
#define SIGNAL_METER_NORMAL_WIDTH (SIGNAL_METER_LEVEL_WIDTH * SIGNAL_METER_LEVEL_COUNT)
#define SIGNAL_METER_PLUS_WIDTH (SIGNAL_METER_LEVEL_WIDTH * 3) /* S9+60 max */
#define SIGNAL_METER_WIDTH (SIGNAL_METER_NORMAL_WIDTH + SIGNAL_METER_PLUS_WIDTH)
#define SIGNAL_METER_HEIGHT 5
#define SIGNAL_METER_Y 75 /*66*/

//#define SIGNAL_METER_RSSI_NORMAL_MIN 25
//#define SIGNAL_METER_RSSI_NORMAL_MAX 67

#define SIGNAL_METER_DBM_S3S9_MIN  134 /*129*/
#define SIGNAL_METER_DBM_S3S9_MAX  93
#define SIGNAL_METER_DBM_S9_PLUS30 63

#define SIGNAL_METER_RSSI_CAL 8
#define SIGNAL_METER_AM_CORR 17 /* 18 */

#endif